# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate
    language: 'cs'

group: !include includes/groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
switch: !include includes/switches.yaml
sensor: !include includes/sensors.yaml
input_boolean: !include includes/input_booleans.yaml
timer: !include includes/timers.yaml
binary_sensor: !include includes/binary_sensors.yaml
media_player: !include includes/media_players.yaml
light: !include includes/lights.yaml
input_select: !include includes/input_selects.yaml
camera: !include includes/cameras.yaml
input_datetime: !include includes/input_datetimes.yaml

google_assistant:
  project_id: home-assistant-new-5b1c8
  service_account: !include secrets/service_account.json
  report_state: true
  
smartir:
  check_updates: false
    
browser_mod:

device_tracker:
  - platform: bluetooth_tracker
    new_device_defaults:
      track_new_devices: false
  - platform: ping
    hosts:
      nokia_6_2_wifi: 192.168.0.103
  
spotify:
  client_id: b5e9102ce29943bba9940ab3fa48a814
  client_secret: !secret spotify_secret
  
vacuum:
  - platform: miio2
    host: 192.168.0.203
    token: !secret xiaomi_vacuum_token
    name: Xiaomi Mop P
    
google:
  client_id: !secret google_id
  client_secret: !secret google_secret
  
ble_monitor:
  devices:
    # sensor
    - mac: 'A4:C1:38:19:A0:D6'
      name: 'Living Room Temperature Sensor'
      encryption_key: !secret xiaomi_temp_sensor_key