# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate
    language: 'cs'

group: !include includes/groups.yaml
automation: !include includes/automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include includes/sensors.yaml
input_boolean: !include includes/input_booleans.yaml
timer: !include includes/timers.yaml
binary_sensor: !include includes/binary_sensors.yaml
media_player: !include includes/media_players.yaml
light: !include includes/lights.yaml
input_select: !include includes/input_selects.yaml

google_assistant:
  project_id: home-assistant-new-5b1c8
  service_account: !include secrets/service_account.json
  report_state: true
  
smartir:
    
browser_mod:

device_tracker:
  - platform: bluetooth_tracker
  
spotify:
  client_id: b5e9102ce29943bba9940ab3fa48a814
  client_secret: !secret spotify_secret