# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
input_boolean: !include input_booleans.yaml
timer: !include timers.yaml

google_assistant:
  project_id: home-assistant-55697
  service_account: !include secrets/service_account.json
  report_state: true
  expose_by_default: false
  exposed_domains:
    - switch
    - light
    - scene
    - media_player
    - input_boolean
    - script